In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
# write your code here ^_^
x = np.array([1, 1, 1])
x

array([1, 1, 1])

## Q#2: Create y array with elements equal to 0.

In [3]:
# write your code here ^_^
y = np.array([0, 0, 0])
y

array([0, 0, 0])

## Q#3: Add x and y arrays.

In [4]:
# write your code here ^_^
x + y

array([1, 1, 1])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
# write your code here ^_^
print('type = ', x.dtype)
print('number of dimension = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  int32
number of dimension =  1
shape =  (3,)
size =  3


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
# write your code here ^_^
w = np.array(
    [
        [11,12],
        [13,14],
        [15,16]
    ])
#w = np.arange(11,17)
#w = w.reshape(3,2)
w.shape

(3, 2)

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
# write your code here ^_^
newArray = np.column_stack((z,w))
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [9]:
# write your code here ^_^
for r in newArray:
    for i in r:
        print(i)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
# write your code here ^_^
newArray = newArray.transpose()
newArray

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
# write your code here ^_^
newArray -=1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
# write your code here ^_^
print("The smallest value = ", newArray.min())
print("The biggest value = " , newArray.max())

The smallest value =  0
The biggest value =  15


## Q#12: Print the first row of "newArray" using indexing.

In [13]:
# write your code here ^_^
print(newArray[0,:])

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
# write your code here ^_^
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
# write your code here ^_^
print(newArray[[0,2],[0,1]])

[ 0 13]


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
# write your code here ^_^
newArray = newArray.reshape(9,1)
newArray.shape

(9, 1)

## Q#16: Change the shape of "newArray" to (3,2).

In [17]:
# write your code here ^_^
newArray = newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉